version: "3"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: norktown
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: carford
    ports:
      - "5432:5432"
